{
  "openapi": "3.0.0",
  "components": {
    "examples": {},
    "headers": {},
    "parameters": {},
    "requestBodies": {},
    "responses": {},
    "schemas": {
      "UserLoginResponse": {
        "properties": {
          "aToken": {
            "type": "string"
          },
          "rToken": {
            "type": "string"
          }
        },
        "required": ["aToken", "rToken"],
        "type": "object",
        "additionalProperties": false
      },
      "ITsoaSuccessResponse_UserLoginResponse_": {
        "properties": {
          "resultType": {
            "type": "string"
          },
          "error": {
            "type": "number",
            "enum": [null],
            "nullable": true
          },
          "success": {
            "$ref": "#/components/schemas/UserLoginResponse"
          }
        },
        "required": ["resultType", "error", "success"],
        "type": "object",
        "additionalProperties": false
      },
      "ITsoaErrorResponse": {
        "properties": {
          "resultType": {
            "type": "string"
          },
          "error": {
            "properties": {
              "data": {
                "nullable": true
              },
              "reason": {
                "type": "string",
                "nullable": true
              },
              "errorCode": {
                "type": "string"
              }
            },
            "type": "object"
          },
          "success": {
            "type": "number",
            "enum": [null],
            "nullable": true
          }
        },
        "required": ["resultType", "error", "success"],
        "type": "object",
        "additionalProperties": false
      }
    },
    "securitySchemes": {}
  },
  "info": {
    "title": "coffect-be",
    "version": "1.0.0",
    "description": "Coffect BackEnd Repository",
    "license": {
      "name": "ISC"
    },
    "contact": {}
  },
  "paths": {
    "/user/login": {
      "post": {
        "operationId": "Login",
        "responses": {
          "200": {
            "description": "로그인성공",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ITsoaSuccessResponse_UserLoginResponse_"
                }
              }
            }
          },
          "400": {
            "description": "비밀번호 불일치",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ITsoaErrorResponse"
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "resultType": "FAIL",
                      "error": {
                        "errorCode": "EC405",
                        "reason": "비밀번호가 일치하지 않습니다",
                        "data": "비밀번호가 일치하지 않습니다"
                      },
                      "success": null
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "존재하지 않는 아이디",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ITsoaErrorResponse"
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "resultType": "FAIL",
                      "error": {
                        "errorCode": "EC404",
                        "reason": "존재하지 않는 아이디입니다",
                        "data": "존재하지 않는 아이디입니다"
                      },
                      "success": null
                    }
                  }
                }
              }
            }
          }
        },
        "description": "로그인",
        "summary": "로그인",
        "tags": ["User Controller"],
        "security": [],
        "parameters": [],
        "requestBody": {
          "description": "유저아이디, 비밀번호",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "properties": {
                  "userId": {
                    "type": "string"
                  },
                  "userPassword": {
                    "type": "string"
                  }
                },
                "required": ["userId", "userPassword"],
                "type": "object",
                "description": "유저아이디, 비밀번호"
              }
            }
          }
        }
      }
    },
    "/user/refresh": {
      "get": {
        "operationId": "Refresh",
        "responses": {
          "200": {
            "description": "토큰 재발급",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ITsoaSuccessResponse_UserLoginResponse_"
                }
              }
            }
          },
          "400": {
            "description": "헤더 누락값 존재",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ITsoaErrorResponse"
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "resultType": "FAIL",
                      "error": {
                        "errorCode": "EC404",
                        "reason": "누락값이 존재합니다.",
                        "data": "헤더에 토큰이 존재하지 않습니다."
                      },
                      "success": null
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "jwt 토큰 만료",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ITsoaErrorResponse"
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "resultType": "FAIL",
                      "error": {
                        "errorCode": "ERR-1",
                        "reason": "Expired",
                        "data": {
                          "name": "TokenExpiredError",
                          "message": "jwt expired",
                          "expiredAt": "2025-07-14T01:29:15.000Z"
                        }
                      },
                      "success": null
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "토큰 관련 오류 (로그인 정보 없음/엑세스 토큰 오류/토큰 불일치)",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ITsoaErrorResponse"
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "resultType": "FAIL",
                      "error": {
                        "errorCode": "ERR-1",
                        "reason": "JsonWebToken error",
                        "data": {
                          "possibleErrors": [
                            "DB에 사용자 로그인 정보가 존재하지 않습니다. 다시 로그인해주세요",
                            "invalid signature - 엑세스 토큰을 보냄",
                            "유효하지 않은 토큰입니다. - 일치하지 않는 토큰 사용"
                          ]
                        }
                      },
                      "success": null
                    }
                  }
                }
              }
            }
          }
        },
        "description": "토큰검증",
        "summary": "데이터베이스에 토큰이 존재하는지 검증하고, 유효할 경우 새로운 토큰을 발급해준다.",
        "tags": ["User Controller"],
        "security": [],
        "parameters": []
      }
    }
  },
  "servers": [
    {
      "url": "/"
    }
  ]
}
